Feat/index user debt
0xSpaceShard/nimbora-indexer pull request #39
Opened 2024-03-27 10:39 UTC by shardAstronaut

### Description

- Modified the logic to store daily the users debt if it was updated.
- Updated the logic to clean the database.

### Code review notes

- Make use the daily user debt logic is good and the data is stored correctly.

### Checklist:

- [X]  Checked the changes locally.
- [ ]  Created / updated tests (e2e / unit).

2024-03-27 14:55 UTC, ioanSL commented on src/nimbora-liquity/liquity.service.ts
> +          debt = await Liquity_Debt.loadEntity(totalDebtId);
When loading the debt entities, it gets repetitive. Take into account that we not only add data to the DB, but also update existing fields, can you add a function called `loadDebtEntities` with one argument `id` that returns the debt entity or creates a new one if it doesn't exist.

2024-03-27 14:58 UTC, ioanSL requested changes
When loading the debt entities, it gets repetitive. Taking into account that we not only add data to the DB, but also update existing fields, can you add a function called `loadDebtEntities` with one argument `id` that returns the debt entity or creates a new one if it doesn't exist.

2024-04-02 12:52 UTC, shardAstronaut commented
> When loading the debt entities, it gets repetitive. Taking into account that we not only add data to the DB, but also update existing fields, can you add a function called `loadDebtEntities` with one argument `id` that returns the debt entity or creates a new one if it doesn't exist.

It should be fine to keep it as it doesn't affect the core logic, we can refactor the code later if needed.

2024-04-03 07:46 UTC, ioanSL approved these changes
LGTM 👍🏽

2024-04-03 15:22 UTC, merged